ordered_list = ["En Karnevalssaga",
"Odysseus Återkomst",
"Amasonernas Återkomst",
"Alexander Den Store Återkommer",
"Gaius-Caligula",
"Marco Polo",
"Tutankhanmun",
"Pizarro",
"Fantomen på AF",
"DIII",
"Sherlock Holmes",
"Tors Hammare",
"Frankenstein",
"Livet i Revy",
"Leonardo",
"Platon och Dualismen",
"Kiviks Musteri",
"Mata Hari",
"Ivanhoe",
"Möllan Rouge",
"Spartacus",
"Titanic",
"Äppelkungen och de sista snapphanarna",
"GIII",
"Calamity Jane",
"2023 - Ett rymdäventyr",
"Muren",
"Drottning Kristina",
"Fritiof Piraten",
"Falklandskriget",
"Kompani Kivik",
"Svärdet i Stenen",
"Tusen och en Natt",
"Kluedo",
"Heliga Valborg",]
